/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogId = IDL.Nat;
export const Timestamp = IDL.Int;
export const VideoId = IDL.Nat;
export const BlogPost = IDL.Record({
  'id' : BlogId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'thumbnail' : IDL.Text,
  'publishDate' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'excerpt' : IDL.Text,
  'relatedVideoIds' : IDL.Vec(VideoId),
});
export const VideoCategory = IDL.Variant({
  'Documentary' : IDL.Null,
  'History' : IDL.Null,
  'Mystery' : IDL.Null,
  'Horror' : IDL.Null,
});
export const Video = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'thumbnail' : IDL.Text,
  'publishDate' : Timestamp,
  'description' : IDL.Text,
  'youtubeId' : IDL.Text,
  'viewCount' : IDL.Nat,
  'isFeatured' : IDL.Bool,
  'category' : VideoCategory,
  'isTrending' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getBlogPost' : IDL.Func([BlogId], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getFeaturedVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getTrendingVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getVideosByCategory' : IDL.Func(
      [VideoCategory],
      [IDL.Vec(Video)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogId = IDL.Nat;
  const Timestamp = IDL.Int;
  const VideoId = IDL.Nat;
  const BlogPost = IDL.Record({
    'id' : BlogId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'thumbnail' : IDL.Text,
    'publishDate' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'excerpt' : IDL.Text,
    'relatedVideoIds' : IDL.Vec(VideoId),
  });
  const VideoCategory = IDL.Variant({
    'Documentary' : IDL.Null,
    'History' : IDL.Null,
    'Mystery' : IDL.Null,
    'Horror' : IDL.Null,
  });
  const Video = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'thumbnail' : IDL.Text,
    'publishDate' : Timestamp,
    'description' : IDL.Text,
    'youtubeId' : IDL.Text,
    'viewCount' : IDL.Nat,
    'isFeatured' : IDL.Bool,
    'category' : VideoCategory,
    'isTrending' : IDL.Bool,
  });
  
  return IDL.Service({
    'getBlogPost' : IDL.Func([BlogId], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getFeaturedVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getTrendingVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getVideosByCategory' : IDL.Func(
        [VideoCategory],
        [IDL.Vec(Video)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };