/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BlogId = bigint;
export interface BlogPost {
  'id' : BlogId,
  'title' : string,
  'content' : string,
  'thumbnail' : string,
  'publishDate' : Timestamp,
  'tags' : Array<string>,
  'excerpt' : string,
  'relatedVideoIds' : Array<VideoId>,
}
export type Timestamp = bigint;
export interface Video {
  'id' : VideoId,
  'title' : string,
  'thumbnail' : string,
  'publishDate' : Timestamp,
  'description' : string,
  'youtubeId' : string,
  'viewCount' : bigint,
  'isFeatured' : boolean,
  'category' : VideoCategory,
  'isTrending' : boolean,
}
export type VideoCategory = { 'Documentary' : null } |
  { 'History' : null } |
  { 'Mystery' : null } |
  { 'Horror' : null };
export type VideoId = bigint;
export interface _SERVICE {
  'getBlogPost' : ActorMethod<[BlogId], [] | [BlogPost]>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getFeaturedVideos' : ActorMethod<[], Array<Video>>,
  'getTrendingVideos' : ActorMethod<[], Array<Video>>,
  'getVideos' : ActorMethod<[], Array<Video>>,
  'getVideosByCategory' : ActorMethod<[VideoCategory], Array<Video>>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'subscribeNewsletter' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];