/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type VideoId = bigint;
export interface Video {
    id: VideoId;
    title: string;
    thumbnail: string;
    publishDate: Timestamp;
    description: string;
    youtubeId: string;
    viewCount: bigint;
    isFeatured: boolean;
    category: VideoCategory;
    isTrending: boolean;
}
export type Timestamp = bigint;
export interface BlogPost {
    id: BlogId;
    title: string;
    content: string;
    thumbnail: string;
    publishDate: Timestamp;
    tags: Array<string>;
    excerpt: string;
    relatedVideoIds: Array<VideoId>;
}
export type BlogId = bigint;
export enum VideoCategory {
    Documentary = "Documentary",
    History = "History",
    Mystery = "Mystery",
    Horror = "Horror"
}
export interface backendInterface {
    getBlogPost(id: BlogId): Promise<BlogPost | null>;
    getBlogPosts(): Promise<Array<BlogPost>>;
    getFeaturedVideos(): Promise<Array<Video>>;
    getTrendingVideos(): Promise<Array<Video>>;
    getVideos(): Promise<Array<Video>>;
    getVideosByCategory(category: VideoCategory): Promise<Array<Video>>;
    submitContactForm(name: string, email: string, subject: string, message: string): Promise<void>;
    subscribeNewsletter(email: string): Promise<boolean>;
}
import type { BlogPost as _BlogPost, Timestamp as _Timestamp, Video as _Video, VideoCategory as _VideoCategory, VideoId as _VideoId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getBlogPost(arg0: BlogId): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPosts();
            return result;
        }
    }
    async getFeaturedVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedVideos();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedVideos();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingVideos();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingVideos();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideos();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideos();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideosByCategory(arg0: VideoCategory): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByCategory(to_candid_VideoCategory_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByCategory(to_candid_VideoCategory_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async subscribeNewsletter(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeNewsletter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeNewsletter(arg0);
            return result;
        }
    }
}
function from_candid_VideoCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoCategory): VideoCategory {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Video_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Video {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoId;
    title: string;
    thumbnail: string;
    publishDate: _Timestamp;
    description: string;
    youtubeId: string;
    viewCount: bigint;
    isFeatured: boolean;
    category: _VideoCategory;
    isTrending: boolean;
}): {
    id: VideoId;
    title: string;
    thumbnail: string;
    publishDate: Timestamp;
    description: string;
    youtubeId: string;
    viewCount: bigint;
    isFeatured: boolean;
    category: VideoCategory;
    isTrending: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        thumbnail: value.thumbnail,
        publishDate: value.publishDate,
        description: value.description,
        youtubeId: value.youtubeId,
        viewCount: value.viewCount,
        isFeatured: value.isFeatured,
        category: from_candid_VideoCategory_n5(_uploadFile, _downloadFile, value.category),
        isTrending: value.isTrending
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Documentary: null;
} | {
    History: null;
} | {
    Mystery: null;
} | {
    Horror: null;
}): VideoCategory {
    return "Documentary" in value ? VideoCategory.Documentary : "History" in value ? VideoCategory.History : "Mystery" in value ? VideoCategory.Mystery : "Horror" in value ? VideoCategory.Horror : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Array<Video> {
    return value.map((x)=>from_candid_Video_n3(_uploadFile, _downloadFile, x));
}
function to_candid_VideoCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoCategory): _VideoCategory {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoCategory): {
    Documentary: null;
} | {
    History: null;
} | {
    Mystery: null;
} | {
    Horror: null;
} {
    return value == VideoCategory.Documentary ? {
        Documentary: null
    } : value == VideoCategory.History ? {
        History: null
    } : value == VideoCategory.Mystery ? {
        Mystery: null
    } : value == VideoCategory.Horror ? {
        Horror: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
